Improve failure message for live update
mdevctl/mdevctl pull request #122
Opened 2024-09-10 13:37 UTC by jonner

Resolves: https://issues.redhat.com/browse/RHEL-40353

Signed-off-by: Jonathon Jongsma <jjongsma@redhat.com>

2024-09-10 16:26 UTC, fiuczy commented on src/callouts.rs
> +                "Live modification is not supported for this device type. Changing configuration requires stopping and restarting the device."
This removes the hint to the user of mdevctl that a callout script needs to exist which also support the new versioning concept in order to support live modify. It needs to be pointed out that the device driver of the device also needs to support a live update/modify concept which the script can make use of. Maybe a hint to some mdevctl documentation could be of help here to keep the message short?

When reading the message the first time I misunderstood the second sentence by "configuration" being the mdevctl configuration. Maybe changing it to "Changing the device configuration requires stopping and restarting the device."

2024-09-10 16:58 UTC, jonner commented on src/callouts.rs
> +                "Live modification is not supported for this device type. Changing configuration requires stopping and restarting the device."
As demonstrated in the referenced JIRA bug, this error message may be passed up through libvirt and presented to a user who has no idea that anything named `mdevctl` even exists. And this user most likely cannot even do anything about the error. A system administrator will need to install callout scripts for the device if they exist. 

So I think that leaving the detailed information in the `debug!` call will be useful to people who know what they're doing and are trying to debug the issue (maybe we should upgrade it to a `warn!`?). But I think we should make the error message less technical and less confusing to end users by not referencing implementation details.

I think your wording suggestion is good.

2024-09-11 06:22 UTC, fiuczy requested changes
You can add my RB with the suggestion applied.

2024-09-11 06:22 UTC, fiuczy commented on src/callouts.rs
> +                "Live modification is not supported for this device type. Changing configuration requires stopping and restarting the device."
I agree with you. 
Wrt `warn!` instead of `debug!`: I think that the error is enough indication to have a look into the debug logs if life modification is supposed to work for a device.

2024-09-11 06:22 UTC, fiuczy commented on src/callouts.rs
> +                "Live modification is not supported for this device type. Changing configuration requires stopping and restarting the device."
```suggestion
                "Live modification is not supported for this device type. Changing the device configuration requires stopping and restarting the device."
```

2024-09-17 13:12 UTC, fiuczy approved these changes
Not sure why all for checks failed but the change look good to me.
Reviewed-by: Boris Fiuczynski <fiuczy@linux.ibm.com>

2024-09-17 13:25 UTC, jonner commented
Must have been a temporary server failure. I just re-ran them and they all succeeded.

2024-09-17 13:25 UTC, merged

2024-09-17 13:26 UTC, fiuczy commented
Just saw that and was wondering how that happened.